import Head from "next/head";
import { useState } from "react";
import { BsFillMoonStarsFill } from "react-icons/bs";
import { AiFillLinkedin, AiFillGithub, AiFillInstagram } from "react-icons/ai";
import { SiJavascript, SiReact, SiHtml5, SiCss3, SiTailwindcss, SiNodedotjs, SiOracle } from "react-icons/si";
import Image from "next/image";
import avatar from "../../public/avatar.png";
import front from '../../public/front.png';
import back from '../../public/back.png';
import dataBase from '../../public/database.png';
import web1 from '../../public/web1.png';
import web2 from '../../public/web2.png';
import web3 from '../../public/web3.png';
import web4 from '../../public/web4.png';
import web5 from '../../public/web5.png';
import web6 from '../../public/web6.png';

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Lucas Guedes - Dev Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" bg-white px-10 dark:bg-gray-900 md:px-20 lg:px-40">
        
        {/* First Section */}
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between dark:text-white">
            <h1 className="font-burtons text-xl">Lucas Guedes</h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill
                  onClick={() => setDarkMode(!darkMode)}
                  className=" cursor-pointer text-2xl"
                />
              </li>
              <li>
                <a
                  className="bg-gradient-to-r from-cyan-500 text- to-teal-500 text-white px-4 py-2 border-none rounded-md ml-8"
                  href="#"
                >
                  Currículo
                </a>
              </li>
            </ul>
          </nav>
          
          {/* My bio */}
          <div className="text-center p-10 py-10">
            <h2 className="text-5xl py-2 text-teal-600 font-medium dark:text-teal-400 md:text-6xl">
              Lucas Guedes
            </h2>
            <h3 className="text-2xl py-2 dark:text-white md:text-3xl">
              Desenvolvedor Front-end.
            </h3>
            <p className="text-md mb-8 py-5 leading-8 text-gray-800 dark:text-gray-200 max-w-xl mx-auto md:text-xl">
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque consectetur lectus urna, et iaculis libero consectetur sed. Morbi sagittis nisi ut nisl scelerisque, a malesuada nisl faucibus. 
            </p>

            {/* Social buttons */}
            <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600 dark:text-gray-400">
              <a href='#'><AiFillGithub /></a>
              <a href='#'><AiFillLinkedin /></a>
              <a href='#'> <AiFillInstagram /></a>
            </div>
            <div className="mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 relative overflow-hidden mt-20 md:h-96 md:w-96">
              <Image src={avatar} layout="fill" objectFit="cover" alt='avatar 3d do lucas guedes'/>
            </div>
          </div>
        </section>

        {/* Second Section */}
        <section>
          {/* My Knoledges */}
          <div>
            <h3 className="text-3xl py-1 dark:text-white ">Conhecimentos</h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
            Fusce imperdiet elementum est. Duis quis bibendum dolor, nec volutpat nunc. Vivamus scelerisque vitae justo sit amet ornare. Nam nec  <span className="text-teal-500"> agencies </span> mauris eleifend ante imperdiet semper. Mauris <span className="text-teal-500">startups </span> ullamcorper scelerisque odio, id vestibulum sem ultrices id. Nam aliquam, ipsum tincidunt.
            </p>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              I offer from a wide range of services, including brand design,
              programming and teaching.
            </p>
          </div>
          <div className="lg:flex gap-10">
            <div className="text-center shadow-lg p-10 rounded-xl my-10  dark:bg-white flex-1">
              <Image src={front} width={100} height={100} className='mx-auto'/>
              <h3 className="text-lg pt-8 pb-2 font-bold ">
                Sólidos
              </h3>
              
              {/* Icons front end */}
              <div className="text-5xl flex flex-col gap-6 items-center mt-5 md:flex-row md:justify-center md:mt-8">
               <SiJavascript className="rounded-lg text-gray-600 hover:text-gray-800  "/>
               <SiReact className=" text-gray-600 hover:text-gray-800"/>
               <SiHtml5 className=" text-gray-600 hover:text-gray-800" />
               <SiCss3 className=" text-gray-600 hover:text-gray-800" />
               <SiTailwindcss className=" text-gray-600 hover:text-gray-800" />
              </div>
              
            </div>

      
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white flex-1">
              <Image src={back} width={100} height={100} className='mx-auto'/>
              <h3 className="text-lg font-bold pt-8 pb-2 ">
                Em Estudo
              </h3>
          
            {/* Icons back-end */}
            <div className="text-5xl flex flex-col gap-6 items-center mt-5 md:flex-row md:justify-center md:mt-8">
            <SiNodedotjs className=" text-gray-600 hover:text-gray-800"/>
            <SiOracle className=" text-gray-600 hover:text-gray-800"/>
            </div>
            
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white flex-1">
              <Image src={dataBase} width={100} height={100} className='mx-auto'/>
              <h3 className="text-lg font-bold pt-8 pb-2 ">Interesses</h3>
              
            </div>
          </div>
        </section>
        <section className="py-10">
          <div>
            <h3 className="text-3xl py-1 dark:text-white ">Portofolio</h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              Since the beginning of my journey as a freelance designer and
              developer, I've done remote work for
              <span className="text-teal-500"> agencies </span>
              consulted for <span className="text-teal-500">startups </span>
              and collaborated with talanted people to create digital products
              for both business and consumer use.
            </p>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              I offer from a wide range of services, including brand design,
              programming and teaching.
            </p>
          </div>
          <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
            <div className="basis-1/3 flex-1 ">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web1}
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web2}
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web3}
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web4}
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web5}
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web6}
              />
            </div>
          </div>
        </section>
      </main>
    </div>
  );
}
